// Official World Golf Rankings — scraped from ESPN on April 8, 2026
// Source: https://www.espn.com/golf/rankings
// LIV players are included (they earn OWGR points at majors and some events)

export const WORLD_RANKINGS: Record<string, number> = {
  'Scottie Scheffler': 1,
  'Rory McIlroy': 2,
  'Cameron Young': 3,
  'Tommy Fleetwood': 4,
  'J.J. Spaun': 5,
  'Matt Fitzpatrick': 6,
  'Collin Morikawa': 7,
  'Robert MacIntyre': 8,
  'Justin Rose': 9,
  'Xander Schauffele': 10,
  'Chris Gotterup': 11,
  'Russell Henley': 12,
  'Sepp Straka': 13,
  'Hideki Matsuyama': 14,
  'Justin Thomas': 15,
  'Ben Griffin': 16,
  'Ludvig Åberg': 17,
  'Ludvig Aberg': 17,
  'Jacob Bridgeman': 18,
  'Alex Noren': 19,
  'Harris English': 20,
  'Akshay Bhatia': 21,
  'Viktor Hovland': 22,
  'Patrick Reed': 23,
  'Bryson DeChambeau': 24,
  'Min Woo Lee': 25,
  'Keegan Bradley': 26,
  'Maverick McNealy': 27,
  'Si Woo Kim': 28,
  'Ryan Gerard': 29,
  'Jon Rahm': 30,
  'Tyrrell Hatton': 31,
  'Shane Lowry': 32,
  'Sam Burns': 33,
  'Kurt Kitayama': 34,
  'Patrick Cantlay': 35,
  'Nicolai Højgaard': 36,
  'Nicolai Hojgaard': 36,
  'Marco Penge': 37,
  'Daniel Berger': 38,
  'Aaron Rai': 39,
  'Nico Echavarria': 40,
  'Jason Day': 41,
  'Jake Knapp': 42,
  'Michael Kim': 43,
  'Corey Conners': 44,
  'Sam Stevens': 45,
  'Kristoffer Reitan': 46,
  'Michael Brennan': 47,
  'Andrew Novak': 48,
  'Matt McCarty': 49,
  'Brian Harman': 50,
  'Ryan Fox': 51,
  'Gary Woodland': 52,
  'Adam Scott': 53,
  'Pierceson Coody': 54,
  'Ryo Hisatsune': 55,
  'Sami Välimäki': 56,
  'Sami Valimaki': 56,
  'Rasmus Højgaard': 57,
  'Rasmus Hojgaard': 57,
  'Michael Thorbjornsen': 58,
  'Max Greyserman': 59,
  'Thomas Detry': 60,
  'Jordan Spieth': 61,
  'Harry Hall': 62,
  'Jayden Schaper': 63,
  'Johnny Keefer': 64,
  'Rickie Fowler': 65,
  'Matt Wallace': 66,
  'Nick Taylor': 67,
  'Jordan Smith': 68,
  'Rasmus Neergaard-Petersen': 69,
  'Casey Jarvis': 70,
  'Sungjae Im': 71,
  'Patrick Rodgers': 72,
  'Sahith Theegala': 73,
  'Taylor Pendrith': 74,
  'Max McGreevy': 75,
  'Bud Cauley': 76,
  'Aldrich Potgieter': 77,
  'Wyndham Clark': 78,
  'J.T. Poston': 79,
  'Rico Hoey': 80,
  'David Puig': 81,
  'John Parry': 82,
  'Elvis Smylie': 83,
  'Haotong Li': 84,
  'Garrick Higgo': 85,
  'Austin Smotherman': 86,
  'Ricky Castillo': 87,
  'David Lipsky': 88,
  'Matti Schmid': 89,
  'Christiaan Bezuidenhout': 90,
  'Daniel Hillier': 91,
  'Dan Brown': 92,
  'Andrew Putnam': 93,
  'Billy Horschel': 94,
  'Denny McCarthy': 95,
  'Lucas Glover': 96,
  'Adrien Saddier': 97,
  'Chris Kirk': 98,
  'Stephan Jaeger': 99,
  'Thriston Lawrence': 100,
}

export function lookupRank(name: string): number | null {
  const n = name.trim()
  if (WORLD_RANKINGS[n] !== undefined) return WORLD_RANKINGS[n]
  const lower = n.toLowerCase()
  for (const [k, v] of Object.entries(WORLD_RANKINGS)) {
    if (k.toLowerCase() === lower) return v
  }
  return null
}
